markdown        : kramdown
kramdown        :
  entity_output : as_input # &mdash; is output as &mdash;
  smart_quotes  : [39, 39, 34, 34] # decimal for left/right single/double quotes
pygments        : true
contact         : "cse@cse.illinois.edu"
facebook_url    : "https://www.facebook.com/cse.illinois.edu"
github_url      : "https://github.com/uiuc-cse"
cse_prefix      : "http://cse.illinois.edu"
vm_url          : "https://docs.google.com/uc?id=0B4Kr6DYkzkQtd05FekRId05DLXM&amp;export=download"
exclude         : [branding, data, tmp, swc.tpl]
